repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        language: system
        entry: uv run ruff check
        files: "\\.py$"
      - id: format
        name: ruff-format
        language: system
        entry: uv run ruff format
        files: "\\.py$"
      - id: mypy
        name: mypy
        language: system
        entry: uv run mypy
        files: "\\.py$"
