name: Python checks

on:
  push:
    branches: ["main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]

jobs:
  lint:
    name: Check style with Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install dependencies
        run: |
          uv sync --group lint
      - name: Check style with Ruff
        run: |
          uv run ruff check --output-format=github .

  format:
    name: Check format with Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install dependencies
        run: |
          uv sync --group lint
      - name: Check format with Ruff
        run: |
          uv run ruff format --check --diff .

  mypy:
    name: Check type hints with mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install dependencies
        run: |
          uv sync --all-extras
      - name: Check type hints with mypy
        run: |
          uv run mypy --show-error-codes --check-untyped-defs --config-file ./pyproject.toml ./

  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    env:
      PYTEST_ADDOPTS: "--color=yes"
    steps:
      - uses: actions/checkout@v6
      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          uv sync --all-extras
          source .venv/bin/activate
      - name: Copy test_generate and remove __future__ import
        run: |
          for file in tests/test_*.py; do
              if [ -f "$file" ]; then
                  basename=$(basename "$file" .py)
                  sed '/from __future__ import annotations/d' "$file" > "tests/${basename}_no_future.py"
              fi
          done
      - name: Test with pytest
        run: |
          uv run pytest --cov=eyconf --cov-report xml:coverage.xml --junitxml=junit.xml -o junit_family=legacy -v
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
